---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/users":
    get:
      summary: Retrieves all users
      tags:
      - Users
      responses:
        '200':
          description: users found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    phone_number:
                      type: string
                    role:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - phone_number
                  - role
                  - created_at
                  - updated_at
        '404':
          description: users not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
